version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: team_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sunjung
      MYSQL_DATABASE: memberdb
      MYSQL_USER: team03
      MYSQL_PASSWORD: 3team
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d